/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package View;

import Controller.ControllerFactory;
import Controller.CrudOperations;
import Model.CashAccount;
import Model.User;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author glory
 */
public class UserPannel extends javax.swing.JFrame {

    /**
     * Creates new form UserPannel
     */
    private final MainPage mainPage; 
    private final String userID;
    CrudOperations<User> userController = (CrudOperations<User>) ControllerFactory.getController("USER");
    CrudOperations<CashAccount> cashController = (CrudOperations<CashAccount>) ControllerFactory.getController("CASH");
    
    public UserPannel(MainPage mainPage) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.mainPage = mainPage;
        userID = UserLoginWindow.getUserID();
        
        List<User> users = userController.search("=", "accountId", userID);
        
        User user = users.get(0);
        userNIMField.setText(user.getAccountId());
        userNameField.setText(user.getName());
        userGenderField.setText(user.getGender());
        userPhoneField.setText(user.getPhone());
        userEmailField.setText(user.getEmail());
        
        List<CashAccount> cashAccounts = cashController.search("=", "name", user.getName());
        
        int amount = 0;
        if (cashAccounts.size() >= 1) {
            for (CashAccount cash : cashAccounts) {
                amount += cash.getAmount();
            }
        }
        userCashField.setText("Rp" + amount);
        userOldPassField.setText(user.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        userExit1Button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        userNIMField = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userCashField = new javax.swing.JLabel();
        userGenderField = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        userSaveButton = new javax.swing.JButton();
        userPhoneField = new javax.swing.JTextField();
        userEmailField = new javax.swing.JTextField();
        userEditButton = new javax.swing.JButton();
        userNameField = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        userExit2Button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        userSavePassButton = new javax.swing.JButton();
        userNewPassField = new javax.swing.JPasswordField();
        userConfirmPassField = new javax.swing.JPasswordField();
        userOldPassField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");

        userExit1Button.setText("Back To Main Menu");
        userExit1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userExit1ButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("NIM :");

        jLabel4.setText("Nama :");

        jLabel10.setText("Jenis Kelamin :");

        jLabel11.setText("Email :");

        jLabel12.setText("Nomor Telepon :");

        jLabel14.setText("Total Kas yang Telah Dibayar:");

        userSaveButton.setText("Save Changes");
        userSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSaveButtonActionPerformed(evt);
            }
        });

        userPhoneField.setEditable(false);

        userEmailField.setEditable(false);

        userEditButton.setText("Edit Info");
        userEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEditButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userExit1Button)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(userEditButton)
                                .addGap(18, 18, 18)
                                .addComponent(userSaveButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(userGenderField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userCashField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userEmailField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userPhoneField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNIMField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userNIMField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userGenderField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(userEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCashField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userSaveButton)
                    .addComponent(userEditButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(userExit1Button)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("My Proflie", jPanel3);

        userExit2Button.setText("Back To Main Menu");
        userExit2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userExit2ButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Old Password :");

        jLabel8.setText("New Password :");

        jLabel9.setText("Confirm Password :");

        userSavePassButton.setText("Save");
        userSavePassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSavePassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userExit2Button)
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userSavePassButton)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNewPassField)
                            .addComponent(userConfirmPassField)
                            .addComponent(userOldPassField, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(userOldPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(userNewPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(userConfirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(userSavePassButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(userExit2Button)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Change Password", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userExit2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userExit2ButtonActionPerformed
        int x = JOptionPane.showConfirmDialog(
                this, "Confirm Exit!",
                "Confirm",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (x == 0) {
            this.setVisible(false);
            mainPage.setVisible(true);
        }
    }//GEN-LAST:event_userExit2ButtonActionPerformed

    private void userSavePassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSavePassButtonActionPerformed
    try {
        String userInput = userOldPassField.getText();

        List<User> users = userController.search("=", "accountId", userID);
        User user = users.get(0);
        String old_password = user.getPassword();

        if (userOldPassField.getText().equals("")
                || userNewPassField.getText().equals("")
                || userConfirmPassField.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this, "Please Fill All Required Fields",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!(userNewPassField.getText().equals(userConfirmPassField.getText()))) {
            JOptionPane.showMessageDialog(
                    this, "Passwords Don't Match",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!(userInput.equals(old_password))) {
            JOptionPane.showMessageDialog(
                    this, "Wrong Password",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {

            String newPassword = userNewPassField.getText();

            long flag = userController.update("=", "accountId", userID, "password", newPassword);

            if (flag >= 1) {
                JOptionPane.showMessageDialog(
                        this, "Password Was Changed Please Re-Login",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                userOldPassField.setText("");
                userNewPassField.setText("");
                userConfirmPassField.setText("");

                UserLoginWindow userLoginWindow = new UserLoginWindow(this.mainPage);
                this.setVisible(false);
                userLoginWindow.setVisible(true);
                
                File logs = new File("src/util/logs.txt");
                if (!logs.getParentFile().exists()) {
                    logs.getParentFile().mkdirs(); // Buat direktori jika belum ada
                }
                if (!logs.exists()) {
                    logs.createNewFile();
                }

                String newLine = System.getProperty("line.separator");
                FileOutputStream fos = new FileOutputStream(logs, true);
                OutputStreamWriter osw = new OutputStreamWriter(fos);
                PrintWriter pw = new PrintWriter(osw);

                String timeStamp = new SimpleDateFormat("yyyy/MM/dd/ HH:mm:ss").format(Calendar.getInstance().getTime());
                pw.append("Account With ID : " + userID + " Changed His Password @ " + timeStamp + newLine);
                pw.close();
            }
        }
    } catch (IOException ex) {
        Logger.getLogger(UserPannel.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_userSavePassButtonActionPerformed

    private void userEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEditButtonActionPerformed
        userPhoneField.setEditable(true);
        userEmailField.setEditable(true);
    }//GEN-LAST:event_userEditButtonActionPerformed

    private void userSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSaveButtonActionPerformed
        try {
            if (!(userPhoneField.getText().matches("[0-9]*"))) {
                JOptionPane.showMessageDialog(
                    this, "Phone Number Must Be Numric Digits",
                    "Invalid Data Type",
                    JOptionPane.ERROR_MESSAGE);
            } else if (!(userEmailField.getText().matches("[A-Za-z0-9-_.]+@[A-Za-z0-9-_]+[.][a-zA-Z]{2,6}"))) {
                JOptionPane.showMessageDialog(
                    this, "Invalid Email Adress",
                    "Invalid Entry",
                    JOptionPane.ERROR_MESSAGE);
            } else {

                long flag1 = userController.update("=", "accountId", userID, "phone", userPhoneField.getText());
                long flag2 = userController.update("=", "accountId", userID, "email", userEmailField.getText());

                userPhoneField.setEditable(false);
                userEmailField.setEditable(false);

                if (flag1 >= 1 && flag2 >= 1) {
                    JOptionPane.showMessageDialog(
                        this, "Changes Saved",
                        "Scucess",
                        JOptionPane.INFORMATION_MESSAGE);

                    
                    File logs = new File("src/util/logs.txt");
                    if (!logs.getParentFile().exists()) {
                        logs.getParentFile().mkdirs(); // Buat direktori jika belum ada
                    }
                    if (!logs.exists()) {
                        logs.createNewFile();
                    }
                
                    String newLine = System.getProperty("line.separator");
                    FileOutputStream fos = new FileOutputStream(logs, true);
                    OutputStreamWriter osw = new OutputStreamWriter(fos);
                    PrintWriter pw = new PrintWriter(osw);

                    String timeStamp = new SimpleDateFormat("yyyy/MM/dd/ HH:mm:ss").format(Calendar.getInstance().getTime());
                    pw.append("Account With ID : " + userID + " Changed His Info @ " + timeStamp + newLine);
                    pw.close();
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(UserPannel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_userSaveButtonActionPerformed

    private void userExit1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userExit1ButtonActionPerformed
        int x = JOptionPane.showConfirmDialog(
            this, "Confirm Exit!",
            "Confirm",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        if (x == 0) {
            this.setVisible(false);
            mainPage.setVisible(true);
        }
    }//GEN-LAST:event_userExit1ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel userCashField;
    private javax.swing.JPasswordField userConfirmPassField;
    private javax.swing.JButton userEditButton;
    private javax.swing.JTextField userEmailField;
    private javax.swing.JButton userExit1Button;
    private javax.swing.JButton userExit2Button;
    private javax.swing.JLabel userGenderField;
    private javax.swing.JLabel userNIMField;
    private javax.swing.JLabel userNameField;
    private javax.swing.JPasswordField userNewPassField;
    private javax.swing.JTextField userOldPassField;
    private javax.swing.JTextField userPhoneField;
    private javax.swing.JButton userSaveButton;
    private javax.swing.JButton userSavePassButton;
    // End of variables declaration//GEN-END:variables
}
