/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package View;

import Controller.ControllerFactory;
import Controller.CrudOperations;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Model.User;
import java.util.List;

/**
 *
 * @author glory
 */
public class UserLoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form UserLoginWindow
     */
    private static String userID;
    private final MainPage mainPage;
    
    CrudOperations<User> userController = (CrudOperations<User>) ControllerFactory.getController("USER");

    public static String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public UserLoginWindow(MainPage mainPage) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.mainPage = mainPage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userIdField = new javax.swing.JTextField();
        user_password_tf = new javax.swing.JPasswordField();
        userLoginButton = new javax.swing.JButton();
        userBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Login");

        jLabel2.setText("NIM :");

        jLabel3.setText("Password :");

        userIdField.setBackground(new java.awt.Color(241, 241, 241));
        userIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdFieldActionPerformed(evt);
            }
        });

        user_password_tf.setBackground(new java.awt.Color(241, 241, 241));

        userLoginButton.setBackground(new java.awt.Color(153, 153, 153));
        userLoginButton.setText("Login");
        userLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLoginButtonActionPerformed(evt);
            }
        });

        userBackButton.setBackground(new java.awt.Color(153, 153, 153));
        userBackButton.setText("Back");
        userBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(user_password_tf)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(userBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(user_password_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userBackButton)
                    .addComponent(userLoginButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdFieldActionPerformed

    private void userLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLoginButtonActionPerformed
     try {
        boolean loggedin = false;
        
        // Search users in the database
        List<User> users = userController.search("=", "accountId", userIdField.getText());
        for (User s : users) {
            if (userIdField.getText().equals(s.getAccountId()) && new String(user_password_tf.getPassword()).equals(s.getPassword())) {
                loggedin = true;
                this.setUserID(userIdField.getText());
            }
        }

        if (loggedin) {
            UserPannel userpannel = new UserPannel(this.mainPage);
            this.setVisible(false);
            userpannel.setVisible(true);

            File logs = new File("src/util/logs.txt");
            if (!logs.getParentFile().exists()) {
                logs.getParentFile().mkdirs(); // Buat direktori jika belum ada
            }
            if (!logs.exists()) {
                logs.createNewFile();
            }

            String newLine = System.getProperty("line.separator");
            FileOutputStream fos = new FileOutputStream(logs, true);
            OutputStreamWriter osw = new OutputStreamWriter(fos);
            PrintWriter pw = new PrintWriter(osw);

            String timeStamp = new SimpleDateFormat("yyyy/MM/dd/ HH:mm:ss").format(Calendar.getInstance().getTime());
            pw.append("USER ID : " + userIdField.getText() + " Logged In @ " + timeStamp + newLine);
            pw.close();

        } else {
            JOptionPane.showMessageDialog(
                   this, "Wrong Username Or Password",
                    "Login Failed",
                    JOptionPane.ERROR_MESSAGE);
        }

    } catch (IOException ex) {
        Logger.getLogger(UserLoginWindow.class.getName()).log(Level.SEVERE, null, ex);
    } 
    }//GEN-LAST:event_userLoginButtonActionPerformed

    private void userBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBackButtonActionPerformed
        this.setVisible(false);
        mainPage.setVisible(true);
    }//GEN-LAST:event_userBackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton userBackButton;
    private javax.swing.JTextField userIdField;
    private javax.swing.JButton userLoginButton;
    private javax.swing.JPasswordField user_password_tf;
    // End of variables declaration//GEN-END:variables
}
